version: 2

sources:
    - name: src
      database: JAFFLE_SHOP
      schema: jshop
      tables:
        - name: customers
          description: customers data
        - name: items
          description: order items data
        - name: products
          description: products data
        - name: stores
          description: locations data
        - name: supplies
          description: supplies data
        - name: orders
          description: orders data
          config:
            freshness:
              warn_after: {count: 24, period: hour}
              error_after: {count: 48, period: day}
            loaded_at_field: ordered_at::timestamp
